// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgPYtO6P7W1abdzR6PWBVmSnaxncRjp_0',
    appId: '1:663866079818:web:2f044ffc68bc23690e84b3',
    messagingSenderId: '663866079818',
    projectId: 'pingostore-07',
    authDomain: 'pingostore-07.firebaseapp.com',
    storageBucket: 'pingostore-07.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBable0YeNhKiw-_r2vCT23xEDb2WUXHh0',
    appId: '1:663866079818:android:da41255b983d699d0e84b3',
    messagingSenderId: '663866079818',
    projectId: 'pingostore-07',
    storageBucket: 'pingostore-07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLvVTiOVfNOwcIyWIVeIyOjIudpdcTxMU',
    appId: '1:663866079818:ios:943f514e7a626be50e84b3',
    messagingSenderId: '663866079818',
    projectId: 'pingostore-07',
    storageBucket: 'pingostore-07.appspot.com',
    androidClientId: '663866079818-j85pm4lfj1ue2e7ko2rb4qg3jf043vdf.apps.googleusercontent.com',
    iosClientId: '663866079818-6nbvjg2mdgafmsccb77i1sosbj647qe5.apps.googleusercontent.com',
    iosBundleId: 'com.example.pingostore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLvVTiOVfNOwcIyWIVeIyOjIudpdcTxMU',
    appId: '1:663866079818:ios:e994b180f14706cf0e84b3',
    messagingSenderId: '663866079818',
    projectId: 'pingostore-07',
    storageBucket: 'pingostore-07.appspot.com',
    androidClientId: '663866079818-j85pm4lfj1ue2e7ko2rb4qg3jf043vdf.apps.googleusercontent.com',
    iosClientId: '663866079818-30ptg4mc34ok1c6bjeqc79204ohpsi2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.pingostore.RunnerTests',
  );
}
